name: Build a source package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build a .tar.gz source package
        run: |
          export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          git archive --format=tar.gz --prefix=yubikey-manager-qt/ -o yubikey-manager-qt-$REF.tar.gz HEAD
          mkdir deploy
          mv yubikey-manager-qt-$REF.tar.gz deploy

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: yubikey-manager-qt-source-package
          path: deploy
