name: windows 32bit

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v1

      - name: Install swig
        run: choco install swig

      - name: Install Qt and Jom
        run: |
          pip install aqtinstall
          python -m aqt install 5.13.1 windows desktop win32_msvc2017
          wget http://download.qt.io/official_releases/jom/jom.zip -OutFile jom.zip
          7z x jom.zip
        shell: powershell

      - name: Download and prepare pyotherside
        run: |
          wget https://github.com/thp/pyotherside/archive/1.5.3.zip -OutFile pyotherside-1.5.3.zip
          7z x pyotherside-1.5.3.zip
          cd pyotherside-1.5.3
          (Get-Content .\src\qmldir).replace('pyothersideplugin', 'pyothersideplugin1') | Set-Content .\src\qmldir
          Clear-Content python.pri
          Add-Content python.pri "PYTHON_CONFIG = python3-config`nQMAKE_LIBS += -LC:\hostedtoolcache\windows\Python\3.6.8\x86\libs -lpython36`nQMAKE_CXXFLAGS += -IC:\hostedtoolcache\windows\Python\3.6.8\x86\include`n"
        shell: powershell

      - name: Build and install pyotherside
        run: |
          set PATH=D:\a\yubikey-manager-qt\yubikey-manager-qt\Qt5.13.1\5.13.1\msvc2017\bin;D:\a\yubikey-manager-qt\yubikey-manager-qt;%PATH%
          call C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86
          cd pyotherside-1.5.3
          qmake
          jom
          jom install

      - name: Build app
        run: |
          set PATH=C:\hostedtoolcache\windows\Python\3.6.8\x86\Scripts;C:\hostedtoolcache\windows\Python\3.6.8\x86;D:\a\yubikey-manager-qt\yubikey-manager-qt\Qt5.13.1\5.13.1\msvc2017\bin;D:\a\yubikey-manager-qt\yubikey-manager-qt;%PATH%
          call C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86
          qmake
          jom

      - name: Copy ykpers and libusb dll files
        run: |
          wget https://developers.yubico.com/yubikey-personalization/Releases/ykpers-1.20.0-win32.zip -OutFile ykpers-1.20.0-win32.zip
          7z x ykpers-1.20.0-win32.zip
          Copy-Item .\bin\*.dll .\ykman-gui\release -Force

          wget https://github.com/libusb/libusb/releases/download/v1.0.22/libusb-1.0.22.7z -OutFile libusb-1.0.22.7z
          7z x libusb-1.0.22.7z
          Copy-Item .\MS32\dll\*.dll .\ykman-gui\release -Force

          cd .\ykman-gui\release
          wget https://www.python.org/ftp/python/3.6.8/python-3.6.8-embed-win32.zip -OutFile python-3.6.8-embed-win32.zip
          7z x python-3.6.8-embed-win32.zip
        shell: powershell

      - name: Run windeployqt
        run: |
          set PATH=D:\a\yubikey-manager-qt\yubikey-manager-qt\Qt5.13.1\5.13.1\msvc2017\bin;D:\a\yubikey-manager-qt\yubikey-manager-qt;%PATH%
          call C:\"Program Files (x86)\Microsoft Visual Studio"\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat x86
          windeployqt .\ykman-gui\release\ykman-gui.exe --qmldir=.\ykman-gui\qml --no-translations --angle --release

      - name: Copy over files and create .zip archive
        run: |
          Copy-Item .\ykman-gui\pymodules .\ykman-gui\release -recurse
          Get-ChildItem -File -Include *.pyc -Recurse | Remove-Item -Force
          Get-ChildItem -Include __pycache__ -Recurse | Remove-Item -Force
          Get-ChildItem -Include *.cpp -Recurse | Remove-Item -Force
          Get-ChildItem -Include *.obj -Recurse | Remove-Item -Force
          Copy-Item .\ykman-cli\release\ykman.exe .\ykman-gui\release

          $arr = $env:GITHUB_REF -split '/'
          $branch = $arr[2]
          7z a yubikey-manager-qt-$branch-win32.zip .\ykman-gui\release

          mkdir deploy
          cp yubikey-manager-qt-$branch-win32.zip deploy
        shell: powershell

      - name: Run GUI
        shell: powershell
        run: |
          .\ykman-gui\release\ykman-gui.exe --version
          .\ykman-gui\release\ykman-gui.exe --help

      - name: Run CLI
        shell: bash
        run: |
          ./ykman-gui/release/ykman --version
          [[ -z "$(./ykman-gui/release/ykman --version | grep -E "not found|missing")" ]]

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: yubikey-manager-qt-win32
          path: deploy
